#services:
#  postgres:
#    image: postgres:16
#    container_name: postgres
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 2004
#      POSTGRES_DB: mydb
#    ports:
#      - "5433:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    restart: unless-stopped
#    healthcheck:
#      test: ["CMD", "pg_isready", "-U", "postgres"]
#      interval: 5s
#      retries: 5
#      start_period: 10s
#      timeout: 5s
#
#  minio-file-service:
#    image: minio/minio:latest
#    container_name: minio-file-service
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    environment:
#      MINIO_ROOT_USER: admin
#      MINIO_ROOT_PASSWORD: admin12345
#    command: server /data --console-address ":9001"
#    volumes:
#      - minio_data:/data
#    restart: unless-stopped
#
#  app:
#    build: .
#    container_name: minio-app
#    ports:
#      - "8080:8080"
#    environment:
#      DB_HOST: postgres
#      DB_PORT: "5432"
#      DB_USER: postgres
#      DB_PASSWORD: 2004
#      DB_NAME: mydb
#      DB_SSLMODE: disable
#      MINIO_ENDPOINT: minio-file-service:9000
#      MINIO_ACCESS_KEY: admin
#      MINIO_SECRET_KEY: admin12345
#      MINIO_BUCKET: mybucket
#      MINIO_SECURE: "false"
#    depends_on:
#      postgres:
#        condition: service_healthy
#      minio-file-service:
#        condition: service_started
#    restart: unless-stopped
#
#
#volumes:
#  minio_data:
#  pgdata:
